### ISSUE TITLE
Support all Tailscale-supported distributions

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible-role-tailscale#4]
Support all distributions located at <https://pkgs.tailscale.com/stable/>. This is not a prioritized list.

This ticket will track the overall state of each distribution and link to the relevant pull requests.

Supported:
- [ ] Ubuntu 16.04 (Xenial)
- [x] Ubuntu 18.04 LTS (Bionic) - https://github.com/artis3n/ansible-role-tailscale/pull/2
- [ ] Ubuntu 19.10 (Eoan)
- [ ] Ubuntu 20.04 LTS (Focal)
- [ ] Debian Stretch
- [ ] Debian Buster (stable)
- [ ] Debian Bullseye (unstable)
- [ ] Debian Sid (testing)
- [ ] Raspbian Buster
- [x] CentOS 7 - https://github.com/artis3n/ansible-role-tailscale/pull/2
- [ ] CentOS 8
- [ ] Fedora
- [ ] RHEL 8
- [ ] Amazon Linux 2
- [ ] OpenSUSE Leap 15.1
- [ ] OpenSUSE Leap 15.2
- [ ] Arch Linux

Experimental:

- [ ] Windows

Maybe:

- [ ] Static binaries

**Comment by artis3n** [comment]
Converted this into this project, closing
https://github.com/artis3n/ansible-role-tailscale/projects/1
